---
- hosts: all
  become: yes
  vars:
    zabbix_server: "158.160.161.177" 
  tasks:
  -  name: install zabbix centOS
     yum:
        name: "https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
        validate_certs: no
     when:
        ansible_os_family == "RedHat"
  -  name: upgrade all packages
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  -  name: Create agent server
     lineinfile:
       dest: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Server=127.0.0.1'
       line: 'Server={{ zabbix_server }}'
  -  name: Create host name
     lineinfile:
       dest: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Hostname=Zabbix server'
       line: 'Hostname={{ ansible_hostname }}'
  -  name: Ensure apache is running
     ansible.builtin.service:
       name: zabbix-agent.service
       state: started
  handlers:
  -  name: Start zabbix-agent
     systemd:
      name: zabbix-agent.service
      enabled: yes
